# aliases
alias ..='cd ..'
alias ...='cd ../../../'
alias ....='cd ../../../../'
alias back='cd $OLDPWD'
alias c='clear'
alias cd..='cd ..'
alias cp='cp -iv'
alias chmod="chmod -c"
alias chmod="chmod -c"
alias df='df -h -x squashfs -x tmpfs -x devtmpfs'
alias diff='colordiff'
alias egrep='egrep --colour=auto'
alias e="vim -O "
alias E="vim -o "
alias extip='curl icanhazip.com'
alias grep='grep --color=auto'
alias l.=' ls -lhFa --time-style=long-iso --color=auto'
alias ll=' ls'
alias ls=' ls -lhF --time-style=long-iso --color=auto'
alias lsmount='mount |column -t'
alias mkdir='mkdir -pv'
alias ports='netstat -tulanp'
alias h='history'
alias j='jobs -l'
alias mv='mv -iv'
alias speedtest='curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -'
alias sproxy='ssh -p 2099 -D 9090 -q -C -N -f jay@vpn.home-network.io'
alias ssha='eval $(ssh-agent) && ssh-add'
alias svim='sudo vim'
alias tn=' tmux new -s'
alias vdestroy='vagrant destroy'
alias vssh='vagrant ssh'
alias vup='vagrant up'
alias watch='watch -d'
alias weather='curl wttr.in'
alias wget='wget -c'

## get top process eating memory
alias mem5='ps auxf | sort -nr -k 4 | head -5'
alias mem10='ps auxf | sort -nr -k 4 | head -10'

## get top process eating cpu ##
alias cpu5='ps auxf | sort -nr -k 3 | head -5'
alias cpu10='ps auxf | sort -nr -k 3 | head -10'

## List largest directories (aka "ducks")
alias dir5='du -cksh * | sort -hr | head -n 5'
alias dir10='du -cksh * | sort -hr | head -n 10'

# Safetynets
# do not delete / or prompt if deleting more than 3 files at a time #
alias rm='rm -I --preserve-root'

# confirmation #
alias mv='mv -i'
alias cp='cp -i'
alias ln='ln -i'

# Parenting changing perms on / #
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

# reload bash config
alias reload="source ~/.bashrc"

# Manage packages easier
if [ -f /usr/bin/apt ]; then
  alias update='sudo apt update'
  alias upgrade='sudo apt update && sudo apt dist-upgrade && sudo apt autoremove && sudo apt clean'
  alias install='sudo apt install'
fi

if [ -f /usr/bin/pacman ]; then
  alias update='sudo pacman -Syyy'
  alias upgrade='sudo pacman -Syu'
  alias install='sudo pacman -S'
fi


# Safetynets
# do not delete / or prompt if deleting more than 3 files at a time #
alias rm='rm -I --preserve-root'

# confirmation #
alias mv='mv -i'
alias cp='cp -i'
alias ln='ln -i'

# Parenting changing perms on / #
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

# reload bash config
alias reload="source ~/.bashrc"

alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
# some more ls aliases
alias ll='ls -ltrh'
alias la='ls -A'
alias l='ls -CF'
alias vpnc='sudo protonvpn c --cc NL'
alias vpnd='sudo protonvpn d'
alias vpns='sudo protonvpn s'
alias vpnc2='windscribe connect Canal'
alias vpnd2='windscribe disconnect'
mop1='h275-3.cs.rutgers.edu'
mop2='h416-2.cs.rutgers.edu'
mcv1='basic.cs.rutgers.edu'
mcv2='pascal.cs.rutgers.edu'
host1=$mop1
host2=$mcv2
alias rdp1d="xfreerdp /cert-ignore /v:$host1 /size:1920x1140 /u:km1449 /p:9461483617 /auto-reconnect-max-retries:0 /smart-sizing /sound +clipboard -wallpaper"
alias rdp2d="xfreerdp /cert-ignore /v:$host2 /size:1920x1140 /u:km1449 /p:9461483617 /auto-reconnect-max-retries:0 /smart-sizing /sound +clipboard -wallpaper"
alias rdp1g="xfreerdp /g:rdgateway.rutgers.edu /gu:km1449 /gp:modi\@RutgerNetId /v:$host1 /u:km1449 /p:9461483617 /d:rad /auto-reconnect-max-retries:0 /size:1920x1140 /smart-sizing /sound +clipboard -wallpaper"
alias rdp2g="xfreerdp /g:rdgateway.rutgers.edu /gu:km1449 /gp:modi\@RutgerNetId /v:$host2 /u:km1449 /p:9461483617 /d:rad /auto-reconnect-max-retries:0 /size:1920x1140 /smart-sizing /sound +clipboard -wallpaper"

